version: "3"
services:
  master:
    image: redis:4
    network_mode: "host"
    restart: always
    command: [
      '--port 6379',
      '--requirepass "${REDIS_PWD}"',
      '--masterauth "${REDIS_PWD}"',
      '--maxmemory 512mb',
      '--maxmemory-policy volatile-ttl',
    ]
  node-1: &node
    image: redis:4
    depends_on:
      - master
    network_mode: "host"
    restart: always
    command: [
      '--port 6380',
      '--requirepass "${REDIS_PWD}"',
      '--masterauth "${REDIS_PWD}"',
      '--slaveof master 6379',
    ]
  node-2:
    <<: *node
    command: [
      '--port 6381',
      '--requirepass "${REDIS_PWD}"',
      '--slaveof master 6379',
      '--masterauth "${REDIS_PWD}"',
      '--save ""',
    ]

  sentinel-1: &sentinel
    build:
      context: ./build
      dockerfile: Dockerfile
    image: redis-sentinel:dev
    restart: always
    environment:
      - SENTINEL_REDIS_PWD=${REDIS_PWD}
      - SENTINEL_REDIS_IP=${SENTINEL_REDIS_IP}
      - SENTINEL_MASTER_NAME=${SENTINEL_MASTER_NAME}
      - SENTINEL_QUORUM=2
      - SENTINEL_DOWN_AFTER=3000
      - SENTINEL_PORT=26379
    command: [
      '${SENTINEL_CONF_PATH}',
      '--sentinel'
    ]
    network_mode: "host"
    depends_on:
      - master
      - node-1
      - node-2
  sentinel-2:
    <<: *sentinel
    environment:
      - SENTINEL_REDIS_PWD=${REDIS_PWD}
      - SENTINEL_REDIS_IP=${SENTINEL_REDIS_IP}
      - SENTINEL_MASTER_NAME=${SENTINEL_MASTER_NAME}
      - SENTINEL_QUORUM=2
      - SENTINEL_DOWN_AFTER=3000
      - SENTINEL_PORT=26380
  sentinel-3:
    <<: *sentinel
    environment:
      - SENTINEL_REDIS_PWD=${REDIS_PWD}
      - SENTINEL_REDIS_IP=${SENTINEL_REDIS_IP}
      - SENTINEL_MASTER_NAME=${SENTINEL_MASTER_NAME}
      - SENTINEL_QUORUM=2
      - SENTINEL_DOWN_AFTER=3000
      - SENTINEL_PORT=26381
