version: '3'
services:
  mysql:
    image: "mysql:5.7"
    restart: always
    network_mode: "host"
    environment:
      - MYSQL_ROOT_PASSWORD=eccom
      - MYSQL_USER=eccom
      - MYSQL_PASSWORD=eccom
      - TZ=Asia/Shanghai
    volumes:
      - ${MYSQL_VOLUME}:/var/lib/mysql
