version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    restart: unless-stopped
    hostname: zookeeper
    ports:
      - "2181:2181"
    container_name: zookeeper

  # kafka version: 1.1.0
  # scala version: 2.12
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_CREATE_TOPICS: "Event:3:1,Perf:3:1,PerfRaw:3:1,FaultSyslog:3:1"
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_ADVERTISED_HOST_NAME: ${DOCKER_HOSTIP}
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LOG_RETENTION_HOURS: 24
    volumes:
      - ${kafka_data_dir}:/kafka
    depends_on:
      - zookeeper
    container_name: kafka
